// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfturmxtufazwvsosmhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmdHVybXh0dWZhend2c29zbWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDY3NjMsImV4cCI6MjA2OTM4Mjc2M30.w2DUP9arQncLfVqDMt4-GSxqqdyw3XiKELv2GBQPyA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});